package io.github.jdouglas9025.socialmediaapi.entity;

import jakarta.persistence.*;

import java.time.LocalDateTime;

@Entity(name = "Post")
@Table(name = "Posts")
public class PostEntity {
    private final String userId;
    private final String username;
    private final LocalDateTime time;
    private final String caption;
    private final String imageRef;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id; //Post ID - auto-generated by DB

    public PostEntity(String userId, String username, String caption, String imageRef) {
        this.userId = userId;
        this.username = username;
        this.time = LocalDateTime.now();
        this.caption = caption;
        this.imageRef = imageRef;
    }

    public PostEntity() {
        this("", "", "", "");
    }

    public String getUserId() {
        return userId;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public LocalDateTime getTime() {
        return time;
    }

    public String getCaption() {
        return caption;
    }

    public String getImageRef() {
        return imageRef;
    }

    @Override
    public String toString() {
        return "id: " + id + ", username: " + username +
                ", timestamp: " + time + ", caption: " +
                caption + ", image ref:  " + imageRef;
    }
}
